name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: npm ci && npm run build
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
